<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TIP-SAI_OrderV1-0"
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:tns="http://www.tmforum.org/tip/SAI_ord/wsdl/v1-0" 
targetNamespace="http://www.tmforum.org/tip/SAI_ord/wsdl/v1-0">

  <wsdl:import namespace="http://www.tmforum.org/tip/SAI_ord/wsdl/v1-0" 
  location="SAIOrderMessages.wsdl"/>
  <wsdl:portType name="SAI">
  
    <wsdl:operation name="execute_Service_Design_Order">
      <wsdl:input message="tns:execute_Service_Design_Order_Request"/>
      <wsdl:output message="tns:execute_Service_Design_Order_Response"/>
      <wsdl:fault name="execute_Service_Design_Exception" 
					  message="tns:execute_Service_Design_Exception"/>
    </wsdl:operation>    
    
    <wsdl:operation name="execute_Service_FeasibilityCheck_Order">
      <wsdl:input message="tns:execute_Service_FeasibilityCheck_Order_Request"/>
      <wsdl:output message="tns:execute_Service_FeasibilityCheck_Order_Response"/>
      <wsdl:fault name="execute_Service_FeasibilityCheck_Exception" 
					  message="tns:execute_Service_FeasibilityCheck_Exception"/>
    </wsdl:operation>
    
    <wsdl:operation name="execute_Service_Activate_Order">
      <wsdl:input message="tns:execute_Service_Activate_Order_Request"/>
      <wsdl:output message="tns:execute_Service_Activate_Order_Response"/>
      <wsdl:fault name="execute_Service_Activate_Exception" 
					  message="tns:execute_Service_Activate_Exception"/>
    </wsdl:operation>            
  <!--
	...
	-->            
  </wsdl:portType>

</wsdl:definitions>
