<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://www.tmforum.org/mtop/fmw/xsd/hdr/v1" xmlns:not="http://www.tmforum.org/mtop/fmw/xsd/notmsg/v1" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0" name="mTOP-NotificationConsumerV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: NotificationConsumer Service Interface WSDL Messages Module</p>
    <p>Description: This module contains all the mTOP NotificationConsumer Service Interface WSDL message definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.tmforum.org/mtop/fmw/xsd/notmsg/v1" schemaLocation="../../xsd/NotificationMessages.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="notify">
    <wsdl:documentation>
      <p>The notify message.</p>
    </wsdl:documentation>
    <!-- ================ -->
    <wsdl:part name="mtopHeader" element="hdr:header"/>
    <wsdl:part name="mtopBody" element="not:notify"/>
  </wsdl:message>
</wsdl:definitions>
