<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0" name="mTOP-NotificationConsumerV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: NotificationConsumer Service Interface WSDL HTTP Module</p>
    <p>Description: This module contains all the mTOP NotificationConsumer Service Interface WSDL SOAP/HTTP binding definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import location="NotificationConsumer_PortType.wsdl"/>
  <wsdl:binding name="NotificationConsumerSoapHttpBinding" type="tns:NotificationConsumer">
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions of the operations of the NotificationConsumer portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <!-- ================ -->
    <wsdl:operation name="notify">
      <soap:operation soapAction="notify" style="document"/>
      <wsdl:input>
        <soap:header message="tns:notify" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NotificationConsumerHttp">
    <wsdl:port name="NotificationConsumerSoapHttp" binding="tns:NotificationConsumerSoapHttpBinding">
      <wsdl:documentation>
        <p>Example of the NotificationConsumer WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
      </wsdl:documentation>
      <soap:address location="http://aserver/mtosi/NotificationConsumerV1-0"/>
    </wsdl:port>
  </wsdl:service>
  <!-- ================ -->
</wsdl:definitions>
