<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0" name="mTOP-NotificationConsumerV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: NotificationConsumer Service Interface WSDL PortType Module</p>
    <p>Description: This module contains all the mTOP NotificationConsumer Service Interface WSDL portType definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import location="NotificationConsumerMessages.wsdl"/>
  <wsdl:portType name="NotificationConsumer">
    <wsdl:documentation>
      <p>The NotificationConsumer portType (interface)</p>
    </wsdl:documentation>
    <!-- ================ -->
    <wsdl:operation name="notify">
      <wsdl:documentation>
        <p>This is the notify operation used to receive notifications from producer or broker.</p>
      </wsdl:documentation>
      <wsdl:input message="tns:notify"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
