
package ws.v1.tmf854;

import javax.xml.ws.WebFault;
import v1.tmf854.ProcessingFailureExceptionT;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_03-b24-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "ProcessingFailureException", targetNamespace = "tmf854.v1")
public class ProcessingFailureException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ProcessingFailureExceptionT faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ProcessingFailureException(String message, ProcessingFailureExceptionT faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ProcessingFailureException(String message, ProcessingFailureExceptionT faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: v1.tmf854.ProcessingFailureExceptionT
     */
    public ProcessingFailureExceptionT getFaultInfo() {
        return faultInfo;
    }

}
