<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTroubleManagement - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-AlarmHandlingV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rtm/wsdl/ah/v1-0" targetNamespace="http://www.tmforum.org/mtop/rtm/wsdl/ah/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceTroubleManagement</p>
    <p>Module: AlarmHandling Service Interface WSDL HTTP Module</p>
    <p>Description: This module contains all the mTOP AlarmHandling Service Interface WSDL definitions for the Web Service deployment profile with SOAP/HTTP binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rtm/wsdl/ah/v1-0" location="AlarmHandlingPortType.wsdl"/>
  <wsdl:binding name="AlarmHandlingSoapHttpBinding" type="tns:AlarmHandling">
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions of the operations of the AlarmHandling portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="acknowledgeAlarms">
      <soap:operation soapAction="acknowledgeAlarms" style="document"/>
      <wsdl:input>
        <soap:header message="tns:acknowledgeAlarmsRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:acknowledgeAlarmsResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="acknowledgeAlarmsException">
        <soap:fault name="acknowledgeAlarmsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="unacknowledgeAlarms">
      <soap:operation soapAction="unacknowledgeAlarms" style="document"/>
      <wsdl:input>
        <soap:header message="tns:unacknowledgeAlarmsRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:unacknowledgeAlarmsResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="unacknowledgeAlarmsException">
        <soap:fault name="unacknowledgeAlarmsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AlarmHandlingHttp">
    <wsdl:documentation>
      <p>Example of the AlarmHandling WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="AlarmHandlingSoapHttp" binding="tns:AlarmHandlingSoapHttpBinding">
      <soap:address location="http://aserver/mtosi/AlarmHandling"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
