<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceProvisioning - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-EquipmentProvisioningV1-0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rp/wsdl/ep/v1-0" targetNamespace="http://www.tmforum.org/mtop/rp/wsdl/ep/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceProvisioning</p>
    <p>Module: EquipmentProvisioning Service Interface WSDL PortType Module</p>
    <p>Description: This module contains all the mTOP EquipmentProvisioning Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rp/wsdl/ep/v1-0" location="EquipmentProvisioningMessages.wsdl"/>
  <wsdl:portType name="EquipmentProvisioning">
    <wsdl:documentation>
      <p>The EquipmentProvisioning porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="provisionEquipment">
      <wsdl:input message="tns:provisionEquipmentRequest"/>
      <wsdl:output message="tns:provisionEquipmentResponse"/>
      <wsdl:fault name="provisionEquipmentException" message="tns:provisionEquipmentException"/>
    </wsdl:operation>
    <wsdl:operation name="unprovisionEquipment">
      <wsdl:input message="tns:unprovisionEquipmentRequest"/>
      <wsdl:output message="tns:unprovisionEquipmentResponse"/>
      <wsdl:fault name="unprovisionEquipmentException" message="tns:unprovisionEquipmentException"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
