<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/coip/v1-0" name="mTOP-CommonObjectInfoProvisioningV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/coip/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: CommonObjectInfoProvisioning Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP CommonObjectInfoProvisioning Service Interface WSDL SOAP/JMS binding definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import location="CommonObjectInfoProvisioningPortType.wsdl"/>
  <wsdl:binding name="CommonObjectInfoProvisioningSoapJmsBinding" type="tns:CommonObjectInfoProvisioning">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the CommonObjectInfoProvisioning portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <!-- ================ -->
    <wsdl:operation name="setAliasNames">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:header message="tns:setAliasNamesRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:setAliasNamesResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="setAliasNamesException">
        <soap:fault name="setAliasNamesException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="setUserLabel">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:header message="tns:setUserLabelRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:setUserLabelResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="setUserLabelException">
        <soap:fault name="setUserLabelException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="setOwner">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:header message="tns:setOwnerRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:setOwnerResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="setOwnerException">
        <soap:fault name="setOwnerException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="setNetworkAccessDomain">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:header message="tns:setNetworkAccessDomainRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:setNetworkAccessDomainResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="setNetworkAccessDomainException">
        <soap:fault name="setNetworkAccessDomainException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
  </wsdl:binding>
  <wsdl:service name="CommonObjectInfoProvisioningJms">
    <wsdl:port name="CommonObjectInfoProvisioningSoapJms" binding="tns:CommonObjectInfoProvisioningSoapJmsBinding">
      <wsdl:documentation>
        <p>Example of the CommonObjectInfoProvisioning WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
      </wsdl:documentation>
      <soap:address location="jms://aserver/mtosi/CommonObjectInfoProvisioningV1-0"/>
    </wsdl:port>
  </wsdl:service>
  <!-- ================ -->
</wsdl:definitions>
