
package ws.v1.tmf854;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "InventoryRetrievalService", targetNamespace = "tmf854.v1.ws", wsdlLocation = "SolutionSets\\monTmfComplete2\\wsdl\\common\\InventoryRetrieval.wsdl")
public class InventoryRetrievalService
    extends Service
{

    private final static URL INVENTORYRETRIEVALSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/C:/DONNEES/WORK/MTOSI-2/baptiste/mardi-12-06/SolutionSets/monTmfComplete2/wsdl/common/InventoryRetrieval.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        INVENTORYRETRIEVALSERVICE_WSDL_LOCATION = url;
    }

    public InventoryRetrievalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryRetrievalService() {
        super(INVENTORYRETRIEVALSERVICE_WSDL_LOCATION, new QName("tmf854.v1.ws", "InventoryRetrievalService"));
    }

    /**
     * 
     * @return
     *     returns InventoryRetrieval
     */
    @WebEndpoint(name = "InventoryRetrievalHttp")
    public InventoryRetrieval getInventoryRetrievalHttp() {
        return (InventoryRetrieval)super.getPort(new QName("tmf854.v1.ws", "InventoryRetrievalHttp"), InventoryRetrieval.class);
    }

}
