
package ws.v1.tmf854;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Holder;
import v1.tmf854.GetInventoryIteratorT;
import v1.tmf854.GetInventoryResponseT;
import v1.tmf854.GetInventoryT;
import v1.tmf854.HeaderT;
import javax.jws.*;
import javax.xml.ws.*;
import javax.jws.soap.*;
import javax.jws.soap.SOAPBinding.*;
import javax.jws.WebParam.*;

/**
 * 
 *     The MTOSI InventoryRetrieval porttype
 *     
 * 
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "InventoryRetrieval", targetNamespace = "tmf854.v1.ws")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InventoryRetrieval {


    /**
     * 
     *         This is the getInventory request/response operation.
     *       
     * 
     * @param mtosiBody
     * @param mtosiHeader
     * @return
     *     returns v1.tmf854.GetInventoryResponseT
     * @throws ProcessingFailureException
     */
    @WebMethod(action = "getInventory")
    @WebResult(name = "getInventoryResponse", targetNamespace = "tmf854.v1", partName = "mtosiBody")
    public GetInventoryResponseT getInventory(
        @WebParam(mode=Mode.INOUT, name = "header", targetNamespace = "tmf854.v1", header = true,  partName = "mtosiHeader")
        javax.xml.ws.Holder<v1.tmf854.HeaderT> mtosiHeader,
        @WebParam(name = "getInventory", targetNamespace = "tmf854.v1", partName = "mtosiBody")
        GetInventoryT mtosiBody)
        throws ProcessingFailureException
    ;

    /**
     * 
     *         This is the getInventory iterator request/response operation.
     *       
     * 
     * @param mtosiBody
     * @param mtosiHeader
     * @return
     *     returns v1.tmf854.GetInventoryResponseT
     * @throws ProcessingFailureException
     */
    @WebMethod(action = "getInventoryIterator")
    @WebResult(name = "getInventoryResponse", targetNamespace = "tmf854.v1", partName = "mtosiBody")
    public GetInventoryResponseT getInventoryIterator(
        @WebParam(name = "header", targetNamespace = "tmf854.v1", header = true, mode = WebParam.Mode.INOUT, partName = "mtosiHeader")
        Holder<HeaderT> mtosiHeader,
        @WebParam(name = "getInventoryIterator", targetNamespace = "tmf854.v1", partName = "mtosiBody")
        GetInventoryIteratorT mtosiBody)
        throws ProcessingFailureException
    ;

}
