<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0" name="mTOP-NotificationProducerV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: NotificationProducer Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP NotificationProducer Service Interface WSDL SOAP/JMS binding definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import location="NotificationProducerPortType.wsdl"/>
  <wsdl:binding name="NotificationProducerSoapJmsBinding" type="tns:NotificationProducer">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the NotificationProducer portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <!-- ================ -->
    <wsdl:operation name="subscribe">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:header message="tns:subscribeRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:subscribeResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="subscribeException">
        <soap:fault name="subscribeException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="unsubscribe">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:header message="tns:unsubscribeRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:unsubscribeResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="unsubscribeException">
        <soap:fault name="unsubscribeException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NotificationProducerJms">
    <wsdl:port name="NotificationProducerSoapJms" binding="tns:NotificationProducerSoapJmsBinding">
      <wsdl:documentation>
        <p>Example of the NotificationProducer WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
      </wsdl:documentation>
      <soap:address location="jms://aserver/mtosi/NotificationProducerV1-0"/>
    </wsdl:port>
  </wsdl:service>
  <!-- ================ -->
</wsdl:definitions>
