<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0" name="mTOP-NotificationProducerV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: NotificationProducer Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP NotificationProducer Service Interface WSDL portType definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import location="NotificationProducerMessages.wsdl"/>
  <wsdl:portType name="NotificationProducer">
    <wsdl:documentation>
      <p>The NotificationProducer porttype (interface)</p>
    </wsdl:documentation>
    <!-- ================ -->
    <wsdl:operation name="subscribe">
      <wsdl:documentation>
        <p>This is the subscribe operation used to receive subscriptions from consumers.</p>
      </wsdl:documentation>
      <wsdl:input message="tns:subscribeRequest"/>
      <wsdl:output message="tns:subscribeResponse"/>
      <wsdl:fault name="subscribeException" message="tns:subscribeException"/>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="unsubscribe">
      <wsdl:documentation>
        <p>This is the unsubscribe operation used to receive subscription cancellations from consumers.</p>
      </wsdl:documentation>
      <wsdl:input message="tns:unsubscribeRequest"/>
      <wsdl:output message="tns:unsubscribeResponse"/>
      <wsdl:fault name="unsubscribeException" message="tns:unsubscribeException"/>
    </wsdl:operation>
  </wsdl:portType>
  <!-- ================ -->
</wsdl:definitions>
