<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ServiceActivation - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-ServiceComponentActivationInterfaceV1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://www.tmforum.org/mtop/fmw/xsd/hdr/v1" xmlns:scai="http://www.tmforum.org/mtop/sa/xsd/scai/v1" xmlns:tns="http://www.tmforum.org/mtop/sa/wsdl/scai/v1-0" targetNamespace="http://www.tmforum.org/mtop/sa/wsdl/scai/v1-0">
  <wsdl:documentation>
    <p>DDP: ServiceActivation</p>
    <p>Module: ServiceComponentActivationInterface Service Interface WSDL Message Module</p>
    <p>Description: This module contains all the mTOP ServiceComponentActivationInterface Service Interface WSDL message definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.tmforum.org/mtop/sa/xsd/scai/v1" schemaLocation="../../xsd/ServiceComponentActivationInterfaceMessages.xsd"/>
    </xsd:schema>
  </wsdl:types>
</wsdl:definitions>
