<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTroubleManagement - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-AlarmRetrievalV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rtm/wsdl/ar/v1-0" targetNamespace="http://www.tmforum.org/mtop/rtm/wsdl/ar/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceTroubleManagement</p>
    <p>Module: AlarmRetrieval Service Interface WSDL HTTP Module</p>
    <p>Description: This module contains all the mTOP AlarmRetrieval Service Interface WSDL definitions for the Web Service deployment profile with SOAP/HTTP binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rtm/wsdl/ar/v1-0" location="AlarmRetrievalPortType.wsdl"/>
  <wsdl:binding name="AlarmRetrievalSoapHttpBinding" type="tns:AlarmRetrieval">
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions of the operations of the AlarmRetrieval portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    
    <wsdl:operation name="getActiveAlarms">
      <soap:operation soapAction="getActiveAlarms" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getActiveAlarmsRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getActiveAlarmsResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getActiveAlarmsException">
        <soap:fault name="getActiveAlarmsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    
   <wsdl:operation name="getActiveAlarmsIterator">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getActiveAlarmsIteratorRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getActiveAlarmsIteratorResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getActiveAlarmsIteratorException">
        <soap:fault name="getActiveAlarmsIteratorException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
   
    <wsdl:operation name="getActiveAlarmsCount">
      <soap:operation soapAction="getActiveAlarmsCount" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getActiveAlarmsCountRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getActiveAlarmsCountResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getActiveAlarmsCountException">
        <soap:fault name="getActiveAlarmsCountException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AlarmRetrievalHttp">
    <wsdl:documentation>
      <p>Example of the AlarmRetrieval WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="AlarmRetrievalSoapHttp" binding="tns:AlarmRetrievalSoapHttpBinding">
      <soap:address location="http://aserver/mtosi/AlarmRetrieval"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
