<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTroubleManagement - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-MaintenanceControlV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rtm/wsdl/mc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rtm/wsdl/mc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceTroubleManagement</p>
    <p>Module: MaintenanceControl Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP MaintenanceControl Service Interface WSDL definitions for the Web Service deployment profile with SOAP/JMS binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rtm/wsdl/mc/v1-0" location="MaintenanceControlPortType.wsdl"/>
  <wsdl:binding name="MaintenanceControlSoapJmsBinding" type="tns:MaintenanceControl">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the MaintenanceControl portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsdl:operation name="getActiveMaintenanceOperations">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getActiveMaintenanceOperationsRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getActiveMaintenanceOperationsResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getActiveMaintenanceOperationsException">
        <soap:fault name="getActiveMaintenanceOperationsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="performMaintenanceOperation">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:performMaintenanceOperationRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:performMaintenanceOperationResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="performMaintenanceOperationException">
        <soap:fault name="performMaintenanceOperationException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MaintenanceControlJms">
    <wsdl:documentation>
      <p>Example of the MaintenanceControl WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="MaintenanceControlSoapJms" binding="tns:MaintenanceControlSoapJmsBinding">
      <soap:address location="jms://aserver/mtosi/MaintenanceControl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
