<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageResourceInventory - Copyright TeleManagement Forum 2006 -->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="tmforum.mtop.om-mri.v1.ws" targetNamespace="tmforum.mtop.om-mri.v1.ws" name="mTOP-ManageResourceInventory-SOAP-JMS">
  <wsdl:import namespace="tmforum.mtop.om-mri.v1.ws" location="../../bindings/soap_jms/MeRetrieval_SoapJms.wsdl"/>
  <wsdl:service name="Jms_ManageResourceInventory">
    <wsdl:documentation>
      <p>Description of the ManageResourceInventory WS and all its service interfaces with their SOAP/JMS bindings assigned to individual network end-points</p>
      <p>Note that this WSDL document is a deployment example of the ManagedElementRetrieval DDP as a WS relying on a JMS transport. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <!-- ================ -->
    <wsdl:port name="ManagedElementRetrieval" binding="tns:ManagedElementRetrievalSoapJmsBinding">
      <soap:address location="http://aserver/mtosi/v2/ManagedElementRetrieval"/>
    </wsdl:port>
    <!-- ================ -->
  </wsdl:service>
</wsdl:definitions>
