<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageResourceInventory - Copyright TeleManagement Forum 2006 -->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="tmforum.mtop.om-mri.v1-0.ws" targetNamespace="tmforum.mtop.om-mri.v1-0.ws" name="mTOP-ManagedElementRetrieval-SOAP-HTTP">
  <wsdl:import namespace="tmforum.mtop.om-mri.v1-0.ws" location="../../portTypes/MeRetrieval_Rpc_PortType.wsdl"/>
  <wsdl:binding name="ManagedElementRetrievalSoapHttpBinding" type="tns:ManagedElementRetrieval_RPC">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions of the operations of the ManagedElementRetrieval_RPC portType (interface)</p>
    </wsdl:documentation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElementNames">
      <wsdl:input>
        <soap:header message="tns:getAllManagedElementNames" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllManagedElementNamesResponse" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllManagedElementNamesException">
        <soap:fault name="getAllManagedElementNamesException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElementNamesIterator">
      <wsdl:input>
        <soap:header message="tns:getAllManagedElementNamesIterator" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllManagedElementNamesResponse" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllManagedElementNamesIteratorException">
        <soap:fault name="getAllManagedElementNamesIteratorException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElements">
      <wsdl:input>
        <soap:header message="tns:getAllManagedElements" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllManagedElementsResponse" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllManagedElementsException">
        <soap:fault name="getAllManagedElementsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElementsIterator">
      <wsdl:input>
        <soap:header message="tns:getAllManagedElementsIterator" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllManagedElementsResponse" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllManagedElementsIteratorException">
        <soap:fault name="getAllManagedElementsIteratorException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
  </wsdl:binding>
</wsdl:definitions>
