<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TIP-GenericOrderV1-0" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:tns="http://www.tmforum.org/tip/gord/wsdl/v1-0" 
targetNamespace="http://www.tmforum.org/tip/gord/wsdl/v1-0">

  <wsdl:import namespace="http://www.tmforum.org/tip/gord/wsdl/v1-0" 
  location="GenericOrderMessages.wsdl"/>
  <wsdl:portType name="GenericOrder">
    <wsdl:operation name="startOrder">
      <wsdl:input message="tns:startOrderRequest"/>
      <wsdl:output message="tns:startOrderResponse"/>
      <wsdl:fault name="startOrderException" message="tns:startOrderException"/>
    </wsdl:operation>
    <wsdl:operation name="suspendOrder">
      <wsdl:input message="tns:suspendOrderRequest"/>
      <wsdl:output message="tns:suspendOrderResponse"/>
      <wsdl:fault name="suspendOrderException" message="tns:suspendOrderException"/>
    </wsdl:operation>
    <wsdl:operation name="resumeOrder">
      <wsdl:input message="tns:resumeOrderRequest"/>
      <wsdl:output message="tns:resumeOrderResponse"/>
      <wsdl:fault name="resumeOrderException" message="tns:resumeOrderException"/>
    </wsdl:operation>
    <wsdl:operation name="abortOrder">
      <wsdl:input message="tns:abortOrderRequest"/>
      <wsdl:output message="tns:abortOrderResponse"/>
      <wsdl:fault name="abortOrderException" message="tns:abortOrderException"/>
    </wsdl:operation>    
  </wsdl:portType>
  <!--
	...
	-->
</wsdl:definitions>
