<?xml version="1.0" encoding="UTF-8"?>
<!-- 编辑使用 XMLSpy v2006 U (http://www.altova.com) 由 any (any) -->
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/mart/v1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/mart/v1-0" name="mTOP-MARTV1-0">
	<wsdl:import location="Mart_Messages.wsdl"/>
	<wsdl:portType name="Mart">
		<wsdl:documentation>
			<p>The MART portType (interface)</p>
		</wsdl:documentation>
		<!-- ================ -->
		<wsdl:operation name="mart">
			<wsdl:documentation>
				<p>This is the notify operation used to receive notifications from producer.</p>
			</wsdl:documentation>
			<wsdl:input message="tns:martRequest"/>
			<wsdl:output message="tns:martResponse"/>
			<wsdl:fault name="martException" message="tns:martException"/>
		</wsdl:operation>
		<!-- ================ -->
		<wsdl:operation name="getProgress">
			<wsdl:documentation>
				<p>This is the get progress operation used to get the state of a running MART operation.</p>
			</wsdl:documentation>
			<wsdl:input message="tns:martGetProgressRequest"/>
			<wsdl:output message="tns:martGetProgressResponse"/>
			<wsdl:fault name="martException" message="tns:martException"/>
		</wsdl:operation>
		<!-- ================ -->
		<wsdl:operation name="termination">
			<wsdl:documentation>
				<p>This is the termination operation used to terminate the running MART operation.</p>
			</wsdl:documentation>
			<wsdl:input message="tns:martTerminationRequest"/>
			<wsdl:output message="tns:martTerminationResponse"/>
			<wsdl:fault name="martException" message="tns:martException"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:documentation>
		<p>DDP: Framework</p>
		<p>Module: MART Interface WSDL PortType Module</p>
		<p>Description: This module contains all the mTOP MART Interface WSDL portType definitions.</p>
		<p>Version: 1.0</p>
	</wsdl:documentation>
</wsdl:definitions>
