<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageResourceInventory - Copyright TeleManagement Forum 2006 -->
<wsdl:definitions  name="mTOP-ManagedElementRetrieval" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mtop.mri="tmforum.mtop.om-mri.v1-0" xmlns:mtop.basic="tmforum.mtop.dm-basic.v1-0" xmlns:tns="tmforum.mtop.om-mri.v1-0.ws" targetNamespace="tmforum.mtop.om-mri.v1-0.ws">
  <wsdl:types>
    <wsdl:documentation>
      <p>All WSDL definitions of the TerminationPointRetrieval mTOP Service Interface messages</p>
    </wsdl:documentation>
    <xsd:schema targetNamespace="tmforum.mtop.om-mri.v1-0.ws">
      <xsd:import namespace="tmforum.mtop.dm-basic.v1-0" schemaLocation="../../../../../DM/Basic/v1-0/xsd/MessageDefinitions.xsd"/>
      <xsd:import namespace="tmforum.mtop.om-mri.v1-0" schemaLocation="../../xsd/CommonRetrieval.xsd"/>
      <xsd:import namespace="tmforum.mtop.om-mri.v1-0" schemaLocation="../../xsd/TpRetrieval.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="">
    <!-- ================ -->
    <wsdl:documentation>
      <p>The  request message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtosiHeader" element="mtop.basic:header"/>
    <wsdl:part name="mtosiBody" element="mtop.mri:"/>
  </wsdl:message>
  <wsdl:message name="Response">
    <!-- ================ -->
    <wsdl:documentation>
      <p>The  response message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtosiHeader" element="mtop.basic:header"/>
    <wsdl:part name="mtosiBody" element="mtop.mri:"/>
  </wsdl:message>
  <wsdl:message name="Exception">
    <!-- ================ -->
    <wsdl:documentation>
      <p>The  exception message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtosiBody" element="mtop.mri:"/>
  </wsdl:message>
  <wsdl:message name="Iterator">
    <!-- ================ -->
    <wsdl:documentation>
      <p>The  iterator request message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtosiHeader" element="mtop.basic:header"/>
    <wsdl:part name="mtosiBody" element="mtop.mri:"/>
  </wsdl:message>
</wsdl:definitions>
