<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceProvisioning - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-TrafficConditioningProfileControlV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rp/wsdl/tcpc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rp/wsdl/tcpc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceProvisioning</p>
    <p>Module: TrafficConditioningProfileControl Service Interface WSDL HTTP Module</p>
    <p>Description: This module contains all the mTOP TrafficConditioningProfileControl Service Interface WSDL definitions for the Web Service deployment profile with SOAP/HTTP binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rp/wsdl/tcpc/v1-0" location="TrafficConditioningProfileControlPortType.wsdl"/>
  <wsdl:binding name="TrafficConditioningProfileControlSoapHttpBinding" type="tns:TrafficConditioningProfileControl">
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions of the operations of the TrafficConditioningProfileControl portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="createTcProfile">
      <soap:operation soapAction="createTcProfile" style="document"/>
      <wsdl:input>
        <soap:header message="tns:createTcProfileRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:createTcProfileResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="createTcProfileException">
        <soap:fault name="createTcProfileException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="deleteTcProfile">
      <soap:operation soapAction="deleteTcProfile" style="document"/>
      <wsdl:input>
        <soap:header message="tns:deleteTcProfileRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:deleteTcProfileResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="deleteTcProfileException">
        <soap:fault name="deleteTcProfileException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="modifyTcProfile">
      <soap:operation soapAction="modifyTcProfile" style="document"/>
      <wsdl:input>
        <soap:header message="tns:modifyTcProfileRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:modifyTcProfileResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="modifyTcProfileException">
        <soap:fault name="modifyTcProfileException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TrafficConditioningProfileControlHttp">
    <wsdl:documentation>
      <p>Example of the TrafficConditioningProfileControl WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="TrafficConditioningProfileControlSoapHttp" binding="tns:TrafficConditioningProfileControlSoapHttpBinding">
      <soap:address location="http://aserver/mtosi/TrafficConditioningProfileControl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
