<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageResourceInventory - Copyright TeleManagement Forum 2006 -->
<wsdl:definitions name="mTOP-ManagedElementRetrieval" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="tmforum.mtop.om-mri.v1-0.ws" xmlns:tns="tmforum.mtop.om-mri.v1-0.ws">
  <wsdl:import namespace="tmforum.mtop.om-mri.v1-0.ws" location="../messages/MeRetrieval_Messages.wsdl"/>
  <wsdl:portType name="ManagedElementRetrieval_RPC">
    <wsdl:documentation>
      <p>The ManagedElementRetrieval porttype (interface) for RPC (synchronous) based client/server communication patterns</p>
    </wsdl:documentation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElementNames">
      <wsdl:documentation>
        <p>This is the getAllManagedElementNames request/response operation</p>
      </wsdl:documentation>
      <wsdl:input message="tns:getAllManagedElementNames"/>
      <wsdl:output message="tns:getAllManagedElementNamesResponse"/>
      <wsdl:fault name="getAllManagedElementNamesException" message="tns:getAllManagedElementNamesException"/>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElementNamesIterator">
      <wsdl:documentation>
        <p>This is the getAllManagedElementNames iterator request/response operation</p>
      </wsdl:documentation>
      <wsdl:input message="tns:getAllManagedElementNamesIterator"/>
      <wsdl:output message="tns:getAllManagedElementNamesResponse"/>
      <wsdl:fault name="getAllManagedElementNamesIteratorException" message="tns:getAllManagedElementNamesIteratorException"/>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElements">
      <wsdl:documentation>
        <p>This is the getAllManagedElements request/response operation</p>
      </wsdl:documentation>
      <wsdl:input message="tns:getAllManagedElements"/>
      <wsdl:output message="tns:getAllManagedElementsResponse"/>
      <wsdl:fault name="getAllManagedElementsException" message="tns:getAllManagedElementsException"/>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElementsIterator">
      <wsdl:documentation>
        <p>This is the getAllManagedElements iterator request/response operation</p>
      </wsdl:documentation>
      <wsdl:input message="tns:getAllManagedElementsIterator"/>
      <wsdl:output message="tns:getAllManagedElementsResponse"/>
      <wsdl:fault name="getAllManagedElementsIteratorException" message="tns:getAllManagedElementsIteratorException"/>
    </wsdl:operation>
    <!-- ================ -->
  </wsdl:portType>
</wsdl:definitions>
