<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourcePerformanceManagement - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-PerformanceManagementControlV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rpm/wsdl/pmc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rpm/wsdl/pmc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourcePerformanceManagement</p>
    <p>Module: PerformanceManagementControl Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP PerformanceManagementControl Service Interface WSDL definitions for the Web Service deployment profile with SOAP/JMS binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rpm/wsdl/pmc/v1-0" location="PerformanceManagementControlPortType.wsdl"/>
  <wsdl:binding name="PerformanceManagementControlSoapJmsBinding" type="tns:PerformanceManagementControl">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the PerformanceManagementControl portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsdl:operation name="clearPerformanceMonitoringData">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:clearPerformanceMonitoringDataRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:clearPerformanceMonitoringDataResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="clearPerformanceMonitoringDataException">
        <soap:fault name="clearPerformanceMonitoringDataException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="disablePerformanceMonitoringData">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:disablePerformanceMonitoringDataRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:disablePerformanceMonitoringDataResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="disablePerformanceMonitoringDataException">
        <soap:fault name="disablePerformanceMonitoringDataException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="enablePerformanceMonitoringData">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:enablePerformanceMonitoringDataRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:enablePerformanceMonitoringDataResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="enablePerformanceMonitoringDataException">
        <soap:fault name="enablePerformanceMonitoringDataException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PerformanceManagementControlJms">
    <wsdl:documentation>
      <p>Example of the PerformanceManagementControl WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="PerformanceManagementControlSoapJms" binding="tns:PerformanceManagementControlSoapJmsBinding">
      <soap:address location="jms://aserver/mtosi/PerformanceManagementControl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
