<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTroubleManagement - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-AlarmControlV1-0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rtm/wsdl/ac/v1-0" targetNamespace="http://www.tmforum.org/mtop/rtm/wsdl/ac/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceTroubleManagement</p>
    <p>Module: AlarmControl Service Interface WSDL PortType Module</p>
    <p>Description: This module contains all the mTOP AlarmControl Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rtm/wsdl/ac/v1-0" location="AlarmControlMessages.wsdl"/>
  <wsdl:portType name="AlarmControl">
    <wsdl:documentation>
      <p>The AlarmControl porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="setAlarmReportingOff">
      <wsdl:input message="tns:setAlarmReportingOffRequest"/>
      <wsdl:output message="tns:setAlarmReportingOffResponse"/>
      <wsdl:fault name="setAlarmReportingOffException" message="tns:setAlarmReportingOffException"/>
    </wsdl:operation>
    <wsdl:operation name="setAlarmReportingOn">
      <wsdl:input message="tns:setAlarmReportingOnRequest"/>
      <wsdl:output message="tns:setAlarmReportingOnResponse"/>
      <wsdl:fault name="setAlarmReportingOnException" message="tns:setAlarmReportingOnException"/>
    </wsdl:operation>
    <wsdl:operation name="setGtpAlarmReportingOff">
      <wsdl:input message="tns:setGtpAlarmReportingOffRequest"/>
      <wsdl:output message="tns:setGtpAlarmReportingOffResponse"/>
      <wsdl:fault name="setGtpAlarmReportingOffException" message="tns:setGtpAlarmReportingOffException"/>
    </wsdl:operation>
    <wsdl:operation name="setGtpAlarmReportingOn">
      <wsdl:input message="tns:setGtpAlarmReportingOnRequest"/>
      <wsdl:output message="tns:setGtpAlarmReportingOnResponse"/>
      <wsdl:fault name="setGtpAlarmReportingOnException" message="tns:setGtpAlarmReportingOnException"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
