<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-NotificationConsumerV1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:notc="http://www.tmforum.org/mtop/fmw/xsd/notmsg/v1" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: NotificationConsumer Service Interface WSDL Module</p>
    <p>Description: This module contains all the mTOP NotificationConsumer Service Interface WSDL definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.tmforum.org/mtop/fmw/xsd/notmsg/v1" schemaLocation="../xsd/NotificationMessagesV1-0.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="notify">
    <wsdl:documentation>
      <p>The notify message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtopBody" element="notc:notify"/>
  </wsdl:message>
  <wsdl:portType name="NotificationConsumer">
    <wsdl:documentation>
      <p>The NotificationConsumer porttype (abstract interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="notify">
      <wsdl:input message="tns:notify"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="NotificationConsumerSoapHttpBinding" type="tns:NotificationConsumer">
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions (concrete interface) of the operations defined in portType</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing wsdl:required="true"/>
    <wsdl:operation name="notify">
      <soap:operation soapAction="notify" style="document"/>
      <wsdl:input>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="NotificationConsumerSoapJmsBinding" type="tns:NotificationConsumer">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions (concrete interface) of the operations defined in portType</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsdl:operation name="notify">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NotificationConsumer">
    <wsdl:documentation>
      <p>Example of the NotificationConsumer WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="NotificationConsumerSoapJms" binding="tns:NotificationConsumerSoapJmsBinding">
      <soap:address location="jms://aserver/mtosi/NotificationConsumer"/>
    </wsdl:port>
    <wsdl:port name="NotificationConsumerSoapHttp" binding="tns:NotificationConsumerSoapHttpBinding">
      <soap:address location="http://aserver/mtosi/NotificationConsumer"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
