<?xml version="1.0" encoding="UTF-8"?>
<!-- TMF NGOSS WS Design Guidelines - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="TMF-SubscriptionManagerV1-0" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notsm/v1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsnt="http://docs.oasis-open.org/wsn/bw-2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notsm/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: CreatePullPoint Service Interface WSDL Module</p>
    <p>Description: This module contains the mTOP CreatePullPoint Service Interface WSDL binding and service definitions based on the OASIS WSN v1.3 Base Notification SubscriptionManager WSDL portType definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://docs.oasis-open.org/wsn/bw-2" location="http://docs.oasis-open.org/wsn/bw-2.wsdl"/>
  <wsdl:binding name="SubscriptionManagerSoapHttpBinding" type="wsnt:PausableSubscriptionManager">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing wsdl:required="true"/>
    <wsdl:operation name="PauseSubscription">
      <soap:operation soapAction="PauseSubscription" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="PauseFailedFault">
        <soap:fault name="PauseFailedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="Renew">
      <soap:operation soapAction="Renew" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnacceptableTerminationTimeFault">
        <soap:fault name="UnacceptableTerminationTimeFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="Unsubscribe">
      <soap:operation soapAction="Unsubscribe" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnableToDestroySubscriptionFault">
        <soap:fault name="UnableToDestroySubscriptionFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ResumeSubscription">
      <soap:operation soapAction="ResumeSubscription" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResumeFailedFault">
        <soap:fault name="ResumeFailedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="SubscriptionManagerSoapJmsBinding" type="wsnt:PausableSubscriptionManager">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsaw:UsingAddressing wsdl:required="true"/>
    <wsdl:operation name="PauseSubscription">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="PauseFailedFault">
        <soap:fault name="PauseFailedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="Renew">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnacceptableTerminationTimeFault">
        <soap:fault name="UnacceptableTerminationTimeFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="Unsubscribe">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnableToDestroySubscriptionFault">
        <soap:fault name="UnableToDestrySubscriptionFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="ResumeSubscription">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="ResumeFailedFault">
        <soap:fault name="ResumeFailedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SubscriptionManager">
    <wsdl:documentation/>
    <wsdl:port binding="tns:SubscriptionManagerSoapHttpBinding" name="SubscriptionManagerHttpPort">
      <soap:address location="http://localhost/SubscriptionManagerV1-0"/>
    </wsdl:port>
    <wsdl:port binding="tns:SubscriptionManagerSoapJmsBinding" name="SubscriptionManagerJmsPort">
      <soap:address location="jms://localhost/SubscriptionManagerV1-0"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
