<?xml version="1.0" encoding="UTF-8"?>
<!-- TMF NGOSS WS Design Guidelines - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="TMF-NotificationConsumerV1-0" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsnt="http://docs.oasis-open.org/wsn/bw-2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notc/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: CreatePullPoint Service Interface WSDL Module</p>
    <p>Description: This module contains the mTOP CreatePullPoint Service Interface WSDL binding and service definitions based on the OASIS WSN v1.3 Base Notification NotificationConsumer WSDL portType definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://docs.oasis-open.org/wsn/bw-2" location="http://docs.oasis-open.org/wsn/bw-2.wsdl"/>
  <wsdl:binding name="NotificationConsumerSoapHttpBinding" type="wsnt:NotificationConsumer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing wsdl:required="true"/>
    <wsdl:operation name="Notify">
      <soap:operation soapAction="Notify" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="NotificationConsumerSoapJmsBinding" type="wsnt:NotificationConsumer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsaw:UsingAddressing wsdl:required="true"/>
    <wsdl:operation name="Notify">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NotificationConsumer">
    <wsdl:documentation/>
    <wsdl:port binding="tns:NotificationConsumerSoapHttpBinding" name="NotificationConsumerHttpPort">
      <soap:address location="http://localhost/NotificationConsumerV1-0"/>
    </wsdl:port>
    <wsdl:port binding="tns:NotificationConsumerSoapJmsBinding" name="NotificationConsumerJmsPort">
      <soap:address location="jms://localhost/NotificationConsumerV1-0"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
