<?xml version="1.0" encoding="UTF-8"?>
<!-- TMF NGOSS WS Design Guidelines - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsnt="http://docs.oasis-open.org/wsn/bw-2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" name="TMF-NotificationProducerV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: CreatePullPoint Service Interface WSDL Module</p>
    <p>Description: This module contains the mTOP CreatePullPoint Service Interface WSDL binding and service definitions based on the OASIS WSN v1.3 Base Notification NotificationProducer WSDL portType definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://docs.oasis-open.org/wsn/bw-2" location="http://docs.oasis-open.org/wsn/bw-2.wsdl"/>
  <wsdl:binding name="NotificationProducerSoapHttpBinding" type="wsnt:NotificationProducer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsaw:UsingAddressing wsdl:required="true"/>
    <wsdl:operation name="Subscribe">
      <soap:operation soapAction="Subscribe" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="SubscribeCreationFailedFault">
        <soap:fault name="SubscribeCreationFailedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TopicExpressionDialectUnknownFault">
        <soap:fault name="TopicExpressionDialectUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidFilterFault">
        <soap:fault name="InvalidFilterFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidTopicExpressionFault">
        <soap:fault name="InvalidTopicExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TopicNotSupportedFault">
        <soap:fault name="TopicNotSupportedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidProducerPropertiesExpressionFault">
        <soap:fault name="InvalidProducerPropertiesExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidMessageContentExpressionFault">
        <soap:fault name="InvalidMessageContentExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnacceptableInitialTerminationTimeFault">
        <soap:fault name="UnacceptableInitialTerminationTimeFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnrecognizedPolicyRequestFault">
        <soap:fault name="UnrecognizedPolicyRequestFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnsupportedPolicyRequestFault">
        <soap:fault name="UnsupportedPolicyRequestFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="NotifyMessageNotSupportedFault">
        <soap:fault name="NotifyMessageNotSupportedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetCurrentMessage">
      <soap:operation soapAction="GetCurrentMessage" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TopicExpressionDialectUnknownFault">
        <soap:fault name="TopicExpressionDialectUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidTopicExpressionFault">
        <soap:fault name="InvalidTopicExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TopicNotSupportedFault">
        <soap:fault name="TopicNotSupportedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="NoCurrentMessageOnTopicFault">
        <soap:fault name="NoCurrentMessageOnTopicFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="MultipleTopicsSpecifiedFault">
        <soap:fault name="MultipleTopicsSpecifiedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="NotificationProducerSoapJmsBinding" type="wsnt:NotificationProducer">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsaw:UsingAddressing wsdl:required="true"/>
    <wsdl:operation name="Subscribe">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="SubscribeCreationFailedFault">
        <soap:fault name="SubscribeCreationFailedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TopicExpressionDialectUnknownFault">
        <soap:fault name="TopicExpressionDialectUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidFilterFault">
        <soap:fault name="InvalidFilterFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidTopicExpressionFault">
        <soap:fault name="InvalidTopicExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TopicNotSupportedFault">
        <soap:fault name="TopicNotSupportedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidProducerPropertiesExpressionFault">
        <soap:fault name="InvalidProducerPropertiesExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidMessageContentExpressionFault">
        <soap:fault name="InvalidMessageContentExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnacceptableInitialTerminationTimeFault">
        <soap:fault name="UnacceptableInitialTerminationTimeFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnrecognizedPolicyRequestFault">
        <soap:fault name="UnrecognizedPolicyRequestFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="UnsupportedPolicyRequestFault">
        <soap:fault name="UnsupportedPolicyRequestFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="NotifyMessageNotSupportedFault">
        <soap:fault name="NotifyMessageNotSupportedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="GetCurrentMessage">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="ResourceUnknownFault">
        <soap:fault name="ResourceUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TopicExpressionDialectUnknownFault">
        <soap:fault name="TopicExpressionDialectUnknownFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="InvalidTopicExpressionFault">
        <soap:fault name="InvalidTopicExpressionFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="TopicNotSupportedFault">
        <soap:fault name="TopicNotSupportedFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="NoCurrentMessageOnTopicFault">
        <soap:fault name="NoCurrentMessageOnTopicFault" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="MultipleTopicsSpecifiedFault">
        <soap:fault name="MultipleTopicsSpecifiedFault" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NotificationProducer">
    <wsdl:documentation/>
    <wsdl:port name="NotificationProducerHttpPort" binding="tns:NotificationProducerSoapHttpBinding">
      <soap:address location="http://localhost/NotificationProducerV1-0"/>
    </wsdl:port>
    <wsdl:port name="NotificationProducerJmsPort" binding="tns:NotificationProducerSoapJmsBinding">
      <soap:address location="jms://localhost/NotificationProducerV1-0"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
