<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM TestManagement - Copyright TeleManagement Forum 2014 -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/tm/wsdl/tsc/v1-0" name="mTOP-TestSpecControl-V1-0" targetNamespace="http://www.tmforum.org/mtop/tm/wsdl/tsc/v1-0">
	<wsdl:import namespace="http://www.tmforum.org/mtop/tm/wsdl/tsc/v1-0" location="TestSpecControlMessages.wsdl"/>
	<wsdl:documentation>
		<p>DDP: Test Management</p>
		<p>Module: Resource Test Spec Control Service Interface WSDL PortType Module</p>
		<p>Description: This module contains all the mTOP Resource Test Spec Control Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
		<p>Version: 1.0</p>
	</wsdl:documentation>
	<wsdl:portType name="TestSpecControl">
		<wsdl:documentation>
			<p>The TestSpecControl porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
		</wsdl:documentation>
		<!-- createTestSpec operation-->
		<wsdl:operation name="createTestSpec">
			<wsdl:input message="tns:createTestSpecRequest"/>
			<wsdl:output message="tns:createTestSpecResponse"/>
			<wsdl:fault name="createTestSpecException" message="tns:createTestSpecException"/>
		</wsdl:operation>
		<!-- modifyTestSpec operation-->
		<wsdl:operation name="modifyTestSpec">
			<wsdl:input message="tns:modifyTestSpecRequest"/>
			<wsdl:output message="tns:modifyTestSpecResponse"/>
			<wsdl:fault name="modifyTestSpecException" message="tns:modifyTestSpecException"/>
		</wsdl:operation>
		<!-- getTestSpec operation-->
		<wsdl:operation name="getTestSpec">
			<wsdl:input message="tns:getTestSpecRequest"/>
			<wsdl:output message="tns:getTestSpecResponse"/>
			<wsdl:fault name="getTestSpecException" message="tns:getTestSpecException"/>
		</wsdl:operation>
		<!-- deleteTestSpec operation-->
		<wsdl:operation name="deleteTestSpec">
			<wsdl:input message="tns:deleteTestSpecRequest"/>
			<wsdl:output message="tns:deleteTestSpecResponse"/>
			<wsdl:fault name="deleteTestSpecException" message="tns:deleteTestSpecException"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
