<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageResourceInventory - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-MultiLayerSubnetworkRetrievalV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/mri/wsdl/mlsnr/v1-0" targetNamespace="http://www.tmforum.org/mtop/mri/wsdl/mlsnr/v1-0">
  <wsdl:documentation>
    <p>DDP: ManageResourceInventory</p>
    <p>Module: MultiLayerSubnetworkRetrieval Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP MultiLayerSubnetworkRetrieval Service Interface WSDL definitions for the Web Service deployment profile with SOAP/JMS binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/mri/wsdl/mlsnr/v1-0" location="MultiLayerSubnetworkRetrievalMessages.wsdl"/>
  <wsdl:portType name="MultiLayerSubnetworkRetrieval_MSG">
    <wsdl:documentation>
      <p>The MultiLayerSubnetworkRetrieval porttype (interface) for MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="getAllMultiLayerSubnetworksWrtOs">
      <wsdl:input message="tns:getAllMultiLayerSubnetworksWrtOsRequest"/>
      <wsdl:output message="tns:getAllMultiLayerSubnetworksWrtOsResponse"/>
      <wsdl:fault name="getAllMultiLayerSubnetworksWrtOsException" message="tns:getAllMultiLayerSubnetworksWrtOsException"/>
    </wsdl:operation>
    <wsdl:operation name="getAllTopLevelMultiLayerSubnetworks">
      <wsdl:input message="tns:getAllTopLevelMultiLayerSubnetworksRequest"/>
      <wsdl:output message="tns:getAllTopLevelMultiLayerSubnetworksResponse"/>
      <wsdl:fault name="getAllTopLevelMultiLayerSubnetworksException" message="tns:getAllTopLevelMultiLayerSubnetworksException"/>
    </wsdl:operation>
    <wsdl:operation name="getContainingMultiLayerSubnetworkNames">
      <wsdl:input message="tns:getContainingMultiLayerSubnetworkNamesRequest"/>
      <wsdl:output message="tns:getContainingMultiLayerSubnetworkNamesResponse"/>
      <wsdl:fault name="getContainingMultiLayerSubnetworkNamesException" message="tns:getContainingMultiLayerSubnetworkNamesException"/>
    </wsdl:operation>
    <wsdl:operation name="getMultiLayerSubnetwork">
      <wsdl:input message="tns:getMultiLayerSubnetworkRequest"/>
      <wsdl:output message="tns:getMultiLayerSubnetworkResponse"/>
      <wsdl:fault name="getMultiLayerSubnetworkException" message="tns:getMultiLayerSubnetworkException"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MultiLayerSubnetworkRetrievalSoapJmsBinding" type="tns:MultiLayerSubnetworkRetrieval_MSG">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the MultiLayerSubnetworkRetrieval MSG portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsdl:operation name="getAllMultiLayerSubnetworksWrtOs">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getAllMultiLayerSubnetworksWrtOsRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllMultiLayerSubnetworksWrtOsResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllMultiLayerSubnetworksWrtOsException">
        <soap:fault name="getAllMultiLayerSubnetworksWrtOsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getAllTopLevelMultiLayerSubnetworks">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getAllTopLevelMultiLayerSubnetworksRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllTopLevelMultiLayerSubnetworksResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllTopLevelMultiLayerSubnetworksException">
        <soap:fault name="getAllTopLevelMultiLayerSubnetworksException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getContainingMultiLayerSubnetworkNames">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getContainingMultiLayerSubnetworkNamesRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getContainingMultiLayerSubnetworkNamesResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getContainingMultiLayerSubnetworkNamesException">
        <soap:fault name="getContainingMultiLayerSubnetworkNamesException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getMultiLayerSubnetwork">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getMultiLayerSubnetworkRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getMultiLayerSubnetworkResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getMultiLayerSubnetworkException">
        <soap:fault name="getMultiLayerSubnetworkException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MultiLayerSubnetworkRetrievalJms">
    <wsdl:documentation>
      <p>Example of the MultiLayerSubnetworkRetrieval WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="MultiLayerSubnetworkRetrievalSoapJms" binding="tns:MultiLayerSubnetworkRetrievalSoapJmsBinding">
      <soap:address location="jms://aserver/mtosi/MultiLayerSubnetworkRetrieval"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
