<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageResourceInventory - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-TransmissionDescriptorRetrievalV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/mri/wsdl/tmdr/v1-0" targetNamespace="http://www.tmforum.org/mtop/mri/wsdl/tmdr/v1-0">
  <wsdl:documentation>
    <p>DDP: ManageResourceInventory</p>
    <p>Module: TransmissionDescriptorRetrieval Service Interface WSDL HTTP Module</p>
    <p>Description: This module contains all the mTOP TransmissionDescriptorRetrieval Service Interface WSDL definitions for the Web Service deployment profile with SOAP/HTTP binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/mri/wsdl/tmdr/v1-0" location="TransmissionDescriptorRetrievalMessages.wsdl"/>
  <wsdl:portType name="TransmissionDescriptorRetrieval_RPC">
    <wsdl:documentation>
      <p>The TransmissionDescriptorRetrieval porttype (interface) for RPC (synchronous) based client/server communication patterns. All SIT operations use the specific get"ObjectType"Iterator operation to handle multiple responses.</p>
    </wsdl:documentation>
    <wsdl:operation name="getAllTransmissionDescriptors">
      <wsdl:input message="tns:getAllTransmissionDescriptorsRequest"/>
      <wsdl:output message="tns:getAllTransmissionDescriptorsResponse"/>
      <wsdl:fault name="getAllTransmissionDescriptorsException" message="tns:getAllTransmissionDescriptorsException"/>
    </wsdl:operation>
    <wsdl:operation name="getAllTransmissionDescriptorsWrtOs">
      <wsdl:input message="tns:getAllTransmissionDescriptorsWrtOsRequest"/>
      <wsdl:output message="tns:getAllTransmissionDescriptorsWrtOsResponse"/>
      <wsdl:fault name="getAllTransmissionDescriptorsWrtOsException" message="tns:getAllTransmissionDescriptorsWrtOsException"/>
    </wsdl:operation>
    <wsdl:operation name="getTransmissionDescriptor">
      <wsdl:input message="tns:getTransmissionDescriptorRequest"/>
      <wsdl:output message="tns:getTransmissionDescriptorResponse"/>
      <wsdl:fault name="getTransmissionDescriptorException" message="tns:getTransmissionDescriptorException"/>
    </wsdl:operation>
    <wsdl:operation name="getTransmissionDescriptorsIterator">
      <wsdl:input message="tns:getTransmissionDescriptorsIteratorRequest"/>
      <wsdl:output message="tns:getTransmissionDescriptorsIteratorResponse"/>
      <wsdl:fault name="getTransmissionDescriptorsIteratorException" message="tns:getTransmissionDescriptorsIteratorException"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="TransmissionDescriptorRetrievalSoapHttpBinding" type="tns:TransmissionDescriptorRetrieval_RPC">
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions of the operations of the TransmissionDescriptorRetrieval RPC portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getAllTransmissionDescriptors">
      <soap:operation soapAction="getAllTransmissionDescriptors" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getAllTransmissionDescriptorsRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllTransmissionDescriptorsResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllTransmissionDescriptorsException">
        <soap:fault name="getAllTransmissionDescriptorsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getAllTransmissionDescriptorsWrtOs">
      <soap:operation soapAction="getAllTransmissionDescriptorsWrtOs" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getAllTransmissionDescriptorsWrtOsRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllTransmissionDescriptorsWrtOsResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllTransmissionDescriptorsWrtOsException">
        <soap:fault name="getAllTransmissionDescriptorsWrtOsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getTransmissionDescriptor">
      <soap:operation soapAction="getTransmissionDescriptor" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getTransmissionDescriptorRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getTransmissionDescriptorResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getTransmissionDescriptorException">
        <soap:fault name="getTransmissionDescriptorException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getTransmissionDescriptorsIterator">
      <soap:operation soapAction="getTransmissionDescriptorsIterator" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getTransmissionDescriptorsIteratorRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getTransmissionDescriptorsIteratorResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getTransmissionDescriptorsIteratorException">
        <soap:fault name="getTransmissionDescriptorsIteratorException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="TransmissionDescriptorRetrievalHttp">
    <wsdl:documentation>
      <p>Example of the TransmissionDescriptorRetrieval WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="TransmissionDescriptorRetrievalSoapHttp" binding="tns:TransmissionDescriptorRetrievalSoapHttpBinding">
      <soap:address location="http://aserver/mtosi/TransmissionDescriptorRetrieval"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
