<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - ResourceProvisioning - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-CommonResourceProvisioningV1-0" targetNamespace="http://www.tmforum.org/mtop/rp/wsdl/crp/v1-0" xmlns:tns="http://www.tmforum.org/mtop/rp/wsdl/crp/v1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
    <p>DDP: ResourceProvisioning</p>
    <p>Module: CommonResourceProvisioning Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP CommonResourceProvisioning Service Interface WSDL SOAP/JMS binding definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rp/wsdl/crp/v1-0" location="CommonResourceProvisioningPortType.wsdl"/>
  <wsdl:binding name="CommonResourceProvisioningSoapJmsBinding" type="tns:CommonResourceProvisioning">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the CommonResourceProvisioning portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <!-- ================ -->
    <wsdl:operation name="setCommonAttributes">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:setCommonAttributesRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:setCommonAttributesResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="setCommonAttributesException">
        <soap:fault name="setCommonAttributesException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CommonResourceProvisioningJms">
    <wsdl:port name="CommonResourceProvisioningSoapJms" binding="tns:CommonResourceProvisioningSoapJmsBinding">
      <wsdl:documentation>
        <p>Example of the CommonResourceProvisioning WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
      </wsdl:documentation>
      <soap:address location="jms://aserver/mtosi/CommonResourceProvisioningV1-0"/>
    </wsdl:port>
  </wsdl:service>
  <!-- ================ -->
</wsdl:definitions>
