<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTestManagement - Copyright TeleManagement Forum 2014 -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rt/wsdl/rtpc/v1-0" name="mTOP-ResourceTestProvisioningControl-V1-0" targetNamespace="http://www.tmforum.org/mtop/rt/wsdl/rtpc/v1-0">
	<wsdl:import namespace="http://www.tmforum.org/mtop/rt/wsdl/rtpc/v1-0" location="ResourceTestProvisioningControlMessages.wsdl"/>
	<wsdl:documentation>
		<p>DDP: ResourceTest Management</p>
		<p>Module: Resource Test Provisioning Control Service Interface WSDL PortType Module</p>
		<p>Description: This module contains all the mTOP Resource Test Provisioning Control Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
		<p>Version: 1.0</p>
	</wsdl:documentation>
	<wsdl:portType name="ResourceTestProvisioningControl">
		<wsdl:documentation>
			<p>The ResourceTestControl porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
		</wsdl:documentation>
		<!-- create and activate flow domain fragment with test operation-->
		<wsdl:operation name="createAndActivateFlowDomainFragmentWithTest">
			<wsdl:input message="tns:createAndActivateFlowDomainFragmentWithTestRequest"/>
			<wsdl:output message="tns:createAndActivateFlowDomainFragmentWithTestResponse"/>
			<wsdl:fault name="createAndActivateFlowDomainFragmentWithTestException" message="tns:createAndActivateFlowDomainFragmentWithTestException"/>
		</wsdl:operation>
			<wsdl:operation name="createAndActivateSubnetworkConnectionWithTest">
			<wsdl:input message="tns:createAndActivateSubnetworkConnectionWithTestRequest"/>
			<wsdl:output message="tns:createAndActivateSubnetworkConnectionWithTestResponse"/>
			<wsdl:fault name="createAndActivateSubnetworkConnectionWithTestException" message="tns:createAndActivateSubnetworkConnectionWithTestException"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
