<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-MartV1-0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/mart/v1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/mart/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: Mart Service Interface WSDL PortType Module</p>
    <p>Description: This module contains all the mTOP Mart Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/fmw/wsdl/mart/v1-0" location="MartMessages.wsdl"/>
  <wsdl:portType name="Mart">
    <wsdl:documentation>
      <p>The Mart porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="doProcess">
      <wsdl:input message="tns:doProcessRequest"/>
      <wsdl:output message="tns:doProcessResponse"/>
      <wsdl:fault name="doProcessException" message="tns:doProcessException"/>
    </wsdl:operation>
    <wsdl:operation name="getProcessState">
      <wsdl:input message="tns:getProcessStateRequest"/>
      <wsdl:output message="tns:getProcessStateResponse"/>
      <wsdl:fault name="getProcessStateException" message="tns:getProcessStateException"/>
    </wsdl:operation>
    <wsdl:operation name="terminateProcess">
      <wsdl:input message="tns:terminateProcessRequest"/>
      <wsdl:output message="tns:terminateProcessResponse"/>
      <wsdl:fault name="terminateProcessException" message="tns:terminateProcessException"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
