<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/coip/v1-0" name="mTOP-CommonObjectInfoProvisioningV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/coip/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: CommonObjectInfoProvisioning Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP CommonObjectInfoProvisioning Service Interface WSDL portType definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import location="CommonObjectInfoProvisioning_Messages.wsdl"/>
  <wsdl:portType name="CommonObjectInfoProvisioning">
    <wsdl:documentation>
      <p>The CommonObjectInfoProvisioning porttype (interface)</p>
    </wsdl:documentation>
    <!-- ================ -->
    <!-- ================ -->
  </wsdl:portType>
</wsdl:definitions>
