<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageResourceInventory - Copyright TeleManagement Forum 2006 -->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="tmforum.mtop.om-mri.v1.ws" targetNamespace="tmforum.mtop.om-mri.v1.ws" name="mTOP-ManagedElementRetrieval-SOAP-JMS">
  <wsdl:import namespace="tmforum.mtop.om-mri.v1.ws" location="../../portTypes/MeRetrieval_Msg_PortType.wsdl"/>
  <wsdl:binding name="ManagedElementRetrievalSoapJmsBinding" type="tns:ManagedElementRetrieval_MSG">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the ManagedElementRetrieval_MSG portType (interface)</p>
    </wsdl:documentation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElementNames">
      <wsdl:input>
        <soap:header message="tns:getAllManagedElementNames" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllManagedElementNamesResponse" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllManagedElementNamesException">
        <soap:fault name="getAllManagedElementNamesException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="getAllManagedElements">
      <wsdl:input>
        <soap:header message="tns:getAllManagedElements" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllManagedElementsResponse" part="mtosiHeader" use="literal"/>
        <soap:body parts="mtosiBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllManagedElementsException">
        <soap:fault name="getAllManagedElementsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
  </wsdl:binding>
  <!-- ================ -->
</wsdl:definitions>
