<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTroubleManagement - Copyright TeleManagement Forum 2008 -->
<wsdl:definitions name="mTOP-AlarmSeverityAssignmentProfileControlV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rtm/wsdl/asapc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rtm/wsdl/asapc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceTroubleManagement</p>
    <p>Module: AlarmSeverityAssignmentProfileControl Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP AlarmSeverityAssignmentProfileControl Service Interface WSDL definitions for the Web Service deployment profile with SOAP/JMS binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rtm/wsdl/asapc/v1-0" location="AlarmSeverityAssignmentProfileControlPortType.wsdl"/>
  <wsdl:binding name="AlarmSeverityAssignmentProfileControlSoapJmsBinding" type="tns:AlarmSeverityAssignmentProfileControl">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the AlarmSeverityAssignmentProfileControl portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsdl:operation name="assignAlarmSeverityAssignmentProfile">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:assignAlarmSeverityAssignmentProfileRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:assignAlarmSeverityAssignmentProfileResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="assignAlarmSeverityAssignmentProfileException">
        <soap:fault name="assignAlarmSeverityAssignmentProfileException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="createAlarmSeverityAssignmentProfile">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:createAlarmSeverityAssignmentProfileRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:createAlarmSeverityAssignmentProfileResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="createAlarmSeverityAssignmentProfileException">
        <soap:fault name="createAlarmSeverityAssignmentProfileException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="deassignAlarmSeverityAssignmentProfile">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:deassignAlarmSeverityAssignmentProfileRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:deassignAlarmSeverityAssignmentProfileResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="deassignAlarmSeverityAssignmentProfileException">
        <soap:fault name="deassignAlarmSeverityAssignmentProfileException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="deleteAlarmSeverityAssignmentProfile">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:deleteAlarmSeverityAssignmentProfileRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:deleteAlarmSeverityAssignmentProfileResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="deleteAlarmSeverityAssignmentProfileException">
        <soap:fault name="deleteAlarmSeverityAssignmentProfileException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="modifyAlarmSeverityAssignmentProfile">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:modifyAlarmSeverityAssignmentProfileRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:modifyAlarmSeverityAssignmentProfileResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="modifyAlarmSeverityAssignmentProfileException">
        <soap:fault name="modifyAlarmSeverityAssignmentProfileException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AlarmSeverityAssignmentProfileControlJms">
    <wsdl:documentation>
      <p>Example of the AlarmSeverityAssignmentProfileControl WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="AlarmSeverityAssignmentProfileControlSoapJms" binding="tns:AlarmSeverityAssignmentProfileControlSoapJmsBinding">
      <soap:address location="jms://aserver/mtosi/AlarmSeverityAssignmentProfileControl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
