package com.bluetetra.maven;

/*
 *
 * Copyright 2001-2006 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Based on an example contributed by Bluetetra Software
 * (from wsdldoc1.1api.zip/Example.java)
 *
 */

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

import com.bluetetra.app.docdb.wsdl.WSDLDocException;
import com.bluetetra.app.driver.WSDLDocGenerator;
import com.bluetetra.app.html.common.CommonHtmlException;
import com.bluetetra.app.html.wsdl.WSDLHtmlException;
import com.bluetetra.app.html.xsd.XSDHtmlException;
import com.bluetetra.app.service.PropertyManager;
import com.bluetetra.lib.service.LogHandler;
import com.bluetetra.lib.wsdl.WSDLException;
import com.bluetetra.lib.xml.XMLIOException;
import com.bluetetra.lib.xsd.XSDException;

/**
 * Build a the WSDL documentation for the current project
 *
 * @author <a href="sgaito@tmforum.org">Stephen Gaito</a>
 * @version $Id $
 * @goal build-wsdl-docs
 * @phase compile
 * requiresProject
 */
public class WSDLdocMojo
    extends AbstractMojo
    implements LogHandler {
    
    /**
     * Path to the Bluetetra WSDLdoc properties file
     * (eg: D:\\WSDLdoc\\config\\wsdldoc.properties)
     *
     * @parameter expression = "${wsdldoc.properties}"
     * @required
     */
    private String propFile;
    
    /**
     * Directory containing the Bluetetra WSDLdoc templates
     * (eg: D:\\WSDLdoc\\template\\default)
     * @parameter expression = "${wsdldoc.template-dir}"
     * @required
     */
    private String templateDir;
    
    /**
     * WSDLdoc generated web-page title
     *
     * @parameter expression = "${wsdldoc.title}" default-value="WSDL documentation generated by Bluetetra\'s WSDLdoc"
     */
    private String title;
    
    /**
     * Input directory which recursively contains the wsdl files
     * (use absolute path if necessary)
     *
     * @parameter expression="${wsdldoc.input-dir}"
     * @required
     */
    private String inputDir;

    /**
     * Regular expression used to filter included wsdl files
     *
     * @parameter expression="${wsdldoc.include-regexp}"
     * @required
     */
    private String includesRegexp;
    private Pattern includesPattern;

    /**
     * Regular expression used to filter excluded wsdl files
     *
     * @parameter expression="${wsdldoc.exclude-regexp}"
     * @required
     */
    private String excludesRegexp;
    private Pattern excludesPattern;

    /**
     * Output directory for the WSDLdoc generated documentation
     * (use absolute path if necessary)
     *
     * @parameter expression="${wsdldoc.output-dir}"
     * @required
     */
    private File outputDir;

    private List wsdlUrlList;

    // find all files with a "wsdl" extension
    public void findAllWSDLfiles(File dir) {
	if (dir.isDirectory()) {
	    // ignore .svn directories
	    if (!dir.toString().contains(".svn")) {
		String[] children = dir.list();
		for (int i=0; i<children.length; i++) {
		    findAllWSDLfiles(new File(dir, children[i]));
		}
	    }
	} else {
	    //add all the xsd and wsdl url here
	    String fileURI = dir.toURI().toString();
	    getLog().debug("Looking at: ["+fileURI+"]");
	    getLog().debug("Using positive: ["+includesPattern.pattern()+"]");
	    if (includesPattern.matcher(fileURI).find()) {
		getLog().debug("Found at: ["+fileURI+"]");
		getLog().debug("Using negative: ["+excludesPattern.pattern()+"]");
		if (!excludesPattern.matcher(fileURI).find()) {
		    getLog().debug("Adding WSDL file: ["+fileURI+"]");
		    wsdlUrlList.add(fileURI);
		}
	    }
	}
    }

    /**
     * Generates the WSDLdoc documentation files.
     *
     * @todo Add license files in META-INF directory.
     */
    public void execute()
        throws MojoExecutionException {

	getLog().debug("WSDLdoc    properties file: ["+propFile+"]");
	getLog().debug("WSDLdoc template directory: ["+templateDir+"]");
	getLog().info("WSDLdoc              title: ["+title+"]");
	getLog().info("WSDLdoc    input directory: ["+inputDir+"]");
	getLog().info("WSDLdoc    includes regExp: ["+includesRegexp+"]");
	getLog().info("WSDLdoc    excludes regExp: ["+excludesRegexp+"]");
	getLog().info("WSDLdoc   output directory: ["+outputDir.toString()+"]\n");

	includesPattern = Pattern.compile(includesRegexp);
	excludesPattern = Pattern.compile(excludesRegexp);

	wsdlUrlList = new ArrayList();

	findAllWSDLfiles(new File(inputDir));

	PropertyManager propertyManager;
      
	try {
	    propertyManager = new PropertyManager (propFile);
	} catch (Exception ex) {
            throw new MojoExecutionException( "Error: Missing WSDLdoc.properties file or config directory.", ex);
	}
        
	//set the directory path to the template files
	propertyManager.setProperty(PropertyManager.template_basedir, 
				    templateDir);

	String hrefPrefix = null; //use null 
	String pathPrefix = null; //use null
	String xmlInstanceDepth = null; //use null
		
	//construct a WSDLDocGenerator object
	WSDLDocGenerator wsdlGen = new WSDLDocGenerator (propertyManager);
	
	try{
	    //Generate documents. Last parameter is the LogHandler
	    wsdlGen.generateDoc (wsdlUrlList, title, outputDir.toString(), 
				 hrefPrefix, pathPrefix, xmlInstanceDepth, 
				 this);
	    
	} catch (XSDException ex0) {    
            throw new MojoExecutionException( "WSDLdoc Error: XSD exception", 
					      ex0 );
	} catch (XMLIOException ex1) {
            throw new MojoExecutionException( "WSDLdoc Error: XML IO exception", 
					      ex1 );
	} catch (WSDLException ex2) {
            throw new MojoExecutionException( "WSDLdoc Error: WSDL exception", 
					      ex2 );
	} catch (WSDLDocException ex3) {
            throw new MojoExecutionException( "WSDLdoc Error: WSDL doc exception", 
					      ex3 );
	} catch (WSDLHtmlException ex4) {
            throw new MojoExecutionException( "WSDLdoc Error: WSDL html exception", 
					      ex4 );
	} catch (XSDHtmlException ex5) {
            throw new MojoExecutionException( "WSDLdoc Error: XSD html exception", 
					      ex5 );
	} catch (CommonHtmlException ex7) {
            throw new MojoExecutionException( "WSDLdoc Error: Common html exception", 
					      ex7 );
	} catch (Exception ex6) {
            throw new MojoExecutionException( "WSDLdoc Error: unknown exception", 
					      ex6 );
	}                       
    }
    

    public void log (String mesg) {
	if (mesg.contains("processing")) {
	    getLog().info(mesg);
	} else {
	    getLog().debug(mesg);
	}
    }
    
    public void warning (String mesg) {
	getLog().warn(mesg);
    }
    
    public void error (String mesg) {
	getLog().error(mesg);
    }
    
    public void fatal (String mesg) {
	getLog().error(mesg);
    }
}