<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - ResourceProvisioning - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-CommonResourceProvisioningV1-0" targetNamespace="http://www.tmforum.org/mtop/rp/wsdl/crp/v1-0" xmlns:tns="http://www.tmforum.org/mtop/rp/wsdl/crp/v1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
    <p>DDP: ResourceProvisioning</p>
    <p>Module: CommonResourceProvisioning Service Interface WSDL PortType Module</p>
    <p>Description: This module contains all the mTOP CommonResourceProvisioning Service Interface WSDL portType definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rp/wsdl/crp/v1-0" location=".\CommonResourceProvisioningMessages.wsdl"/>
  <wsdl:portType name="CommonResourceProvisioning">
    <wsdl:documentation>
      <p>The CommonResourceProvisioning porttype (interface)</p>
    </wsdl:documentation>
    <!-- ================ -->
    <wsdl:operation name="setCommonAttributes">
      <wsdl:documentation>
        <p>This is the setCommonAttributes operation used to receive subscriptions from consumers.</p>
      </wsdl:documentation>
      <wsdl:input message="tns:setCommonAttributesRequest"/>
      <wsdl:output message="tns:setCommonAttributesResponse"/>
      <wsdl:fault name="setCommonAttributesException" message="tns:setCommonAttributesException"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
