<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTroubleManagement - Copyright TeleManagement Forum 2008 -->
<wsdl:definitions name="mTOP-ProtectionControlV1-0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rtm/wsdl/pc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rtm/wsdl/pc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceTroubleManagement</p>
    <p>Module: ProtectionControl Service Interface WSDL PortType Module</p>
    <p>Description: This module contains all the mTOP ProtectionControl Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rtm/wsdl/pc/v1-0" location="ProtectionControlMessages.wsdl"/>
  <wsdl:portType name="ProtectionControl">
    <wsdl:documentation>
      <p>The ProtectionControl porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="performProtectionCommand">
      <wsdl:input message="tns:performProtectionCommandRequest"/>
      <wsdl:output message="tns:performProtectionCommandResponse"/>
      <wsdl:fault name="performProtectionCommandException" message="tns:performProtectionCommandException"/>
    </wsdl:operation>
    
    <wsdl:operation name="createProtectionGroup">
      <wsdl:input message="tns:createProtectionGroupRequest"/>
      <wsdl:output message="tns:createProtectionGroupResponse"/>
      <wsdl:fault name="createProtectionGroupException" message="tns:createProtectionGroupException"/>
    </wsdl:operation>
    
    <wsdl:operation name="deleteProtectionGroup">
      <wsdl:input message="tns:deleteProtectionGroupRequest"/>
      <wsdl:output message="tns:deleteProtectionGroupResponse"/>
      <wsdl:fault name="deleteProtectionGroupException" message="tns:deleteProtectionGroupException"/>
    </wsdl:operation>
    
    <wsdl:operation name="modifyProtectionGroup">
      <wsdl:input message="tns:modifyProtectionGroupRequest"/>
      <wsdl:output message="tns:modifyProtectionGroupResponse"/>
      <wsdl:fault name="modifyProtectionGroupException" message="tns:modifyProtectionGroupException"/>
    </wsdl:operation> 
    
  </wsdl:portType>
</wsdl:definitions>
