<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceProvisioning - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-GuiCutThroughControlV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rp/wsdl/gctc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rp/wsdl/gctc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceProvisioning</p>
    <p>Module: GuiCutThroughControl Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP GuiCutThroughControl Service Interface WSDL definitions for the Web Service deployment profile with SOAP/JMS binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rp/wsdl/gctc/v1-0" location="GuiCutThroughControlPortType.wsdl"/>
  <wsdl:binding name="GuiCutThroughControlSoapJmsBinding" type="tns:GuiCutThroughControl">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the GuiCutThroughControl portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsdl:operation name="destroyGct">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:destroyGctRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:destroyGctResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="destroyGctException">
        <soap:fault name="destroyGctException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getGctProfileInfo">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getGctProfileInfoRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getGctProfileInfoResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getGctProfileInfoException">
        <soap:fault name="getGctProfileInfoException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="launchGct">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:launchGctRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:launchGctResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="launchGctException">
        <soap:fault name="launchGctException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="GuiCutThroughControlJms">
    <wsdl:documentation>
      <p>Example of the GuiCutThroughControl WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="GuiCutThroughControlSoapJms" binding="tns:GuiCutThroughControlSoapJmsBinding">
      <soap:address location="jms://aserver/mtosi/GuiCutThroughControl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
