<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageServiceInventory - Copyright TeleManagement Forum 2008 -->
<wsdl:definitions name="mTOP-ServiceInventoryRetrievalV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/msi/wsdl/sir/v1-0" targetNamespace="http://www.tmforum.org/mtop/msi/wsdl/sir/v1-0">
  <wsdl:documentation>
    <p>DDP: ManageServiceInventory</p>
    <p>Module: ServiceInventoryRetrieval Service Interface WSDL JMS Module</p>
    <p>Description: This module contains all the mTOP ServiceInventoryRetrieval Service Interface WSDL definitions for the Web Service deployment profile with SOAP/JMS binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/msi/wsdl/sir/v1-0" location="ServiceInventoryRetrievalMessages.wsdl"/>
  <wsdl:portType name="ServiceInventoryRetrieval_MSG">
    <wsdl:documentation>
      <p>The ServiceInventoryRetrieval porttype (interface) for MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="getServiceInventory">
      <wsdl:input message="tns:getServiceInventoryRequest"/>
      <wsdl:output message="tns:getServiceInventoryResponse"/>
      <wsdl:fault name="getServiceInventoryException" message="tns:getServiceInventoryException"/>
    </wsdl:operation>
    <wsdl:operation name="getServiceInventoryIterator">
      <wsdl:input message="tns:getServiceInventoryIteratorRequest"/>
      <wsdl:output message="tns:getServiceInventoryIteratorResponse"/>
      <wsdl:fault name="getServiceInventoryIteratorException" message="tns:getServiceInventoryIteratorException"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ServiceInventoryRetrievalSoapJmsBinding" type="tns:ServiceInventoryRetrieval_MSG">
    <wsdl:documentation>
      <p>SOAP JMS binding definitions of the operations of the ServiceInventoryRetrieval MSG portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
    <wsdl:operation name="getServiceInventory">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getServiceInventoryRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getServiceInventoryResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getServiceInventoryException">
        <soap:fault name="getServiceInventoryException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getServiceInventoryIterator">
      <soap:operation style="document"/>
      <wsdl:input>
        <soap:header message="tns:getServiceInventoryIteratorRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getServiceInventoryIteratorResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getServiceInventoryIteratorException">
        <soap:fault name="getServiceInventoryIteratorException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ServiceInventoryRetrievalJms">
    <wsdl:documentation>
      <p>Example of the ServiceInventoryRetrieval WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="ServiceInventoryRetrievalSoapJms" binding="tns:ServiceInventoryRetrievalSoapJmsBinding">
      <soap:address location="jms://aserver/mtosi/ServiceInventoryRetrieval"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
