<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - Framework - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0" name="mTOP-NotificationProducerV1-0" targetNamespace="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0">
  <wsdl:documentation>
    <p>DDP: Framework</p>
    <p>Module: NotificationProducer Service Interface WSDL HTTP Module</p>
    <p>Description: This module contains all the mTOP NotificationProducer Service Interface WSDL SOAP/HTTP binding definitions based on an RPC style port type (interface).</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/fmw/wsdl/notp/v1-0" location="NotificationProducerPortType.wsdl"/>
  <wsdl:binding name="NotificationProducerSoapHttpBinding" type="tns:NotificationProducer">
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions of the operations of the NotificationProducer_RPC portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <!-- ================ -->
    <wsdl:operation name="subscribe">
      <soap:operation soapAction="subscribe" style="document"/>
      <wsdl:input>
        <soap:header message="tns:subscribeRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:subscribeResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="subscribeException">
        <soap:fault name="subscribeException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <!-- ================ -->
    <wsdl:operation name="unsubscribe">
      <soap:operation soapAction="unsubscribe" style="document"/>
      <wsdl:input>
        <soap:header message="tns:unsubscribeRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:unsubscribeResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="unsubscribeException">
        <soap:fault name="unsubscribeException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="NotificationProducerHttp">
    <wsdl:port name="NotificationProducerSoapHttp" binding="tns:NotificationProducerSoapHttpBinding">
      <wsdl:documentation>
        <p>Example of the NotificationProducer WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
      </wsdl:documentation>
      <soap:address location="http://aserver/mtosi/NotificationProducerV1-0"/>
    </wsdl:port>
  </wsdl:service>
  <!-- ================ -->
</wsdl:definitions>
