<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTroubleManagement - Copyright TeleManagement Forum 2008 -->
<wsdl:definitions name="mTOP-ProtectionControlV1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://www.tmforum.org/mtop/fmw/xsd/hdr/v1" xmlns:pc="http://www.tmforum.org/mtop/rtm/xsd/pc/v1" xmlns:tns="http://www.tmforum.org/mtop/rtm/wsdl/pc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rtm/wsdl/pc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceTroubleManagement</p>
    <p>Module: ProtectionControl Service Interface WSDL Message Module</p>
    <p>Description: This module contains all the mTOP ProtectionControl Service Interface WSDL message definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.tmforum.org/mtop/rtm/xsd/pc/v1" schemaLocation="../../xsd/ProtectionControlMessages.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="performProtectionCommandRequest">
    <wsdl:documentation>
      <p>The performProtectionCommand request message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtopHeader" element="hdr:header"/>
    <wsdl:part name="mtopBody" element="pc:performProtectionCommandRequest"/>
  </wsdl:message>
  <wsdl:message name="performProtectionCommandResponse">
    <wsdl:documentation>
      <p>The performProtectionCommand response message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtopHeader" element="hdr:header"/>
    <wsdl:part name="mtopBody" element="pc:performProtectionCommandResponse"/>
  </wsdl:message>
  <wsdl:message name="performProtectionCommandException">
    <wsdl:documentation>
      <p>The performProtectionCommand exception message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtopBody" element="pc:performProtectionCommandException"/>
  </wsdl:message>
</wsdl:definitions>
