<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTroubleManagement - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-AlarmControlV1-0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:hdr="http://www.tmforum.org/mtop/fmw/xsd/hdr/v1" xmlns:ac="http://www.tmforum.org/mtop/rtm/xsd/ac/v1" xmlns:tns="http://www.tmforum.org/mtop/rtm/wsdl/ac/v1-0" targetNamespace="http://www.tmforum.org/mtop/rtm/wsdl/ac/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceTroubleManagement</p>
    <p>Module: AlarmControl Service Interface WSDL Message Module</p>
    <p>Description: This module contains all the mTOP AlarmControl Service Interface WSDL message definitions.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema>
      <xsd:import namespace="http://www.tmforum.org/mtop/rtm/xsd/ac/v1" schemaLocation="../../xsd/AlarmControlMessages.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="setAlarmReportingRequest">
    <wsdl:documentation>
      <p>The setAlarmReporting request message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtopHeader" element="hdr:header"/>
    <wsdl:part name="mtopBody" element="ac:setAlarmReportingRequest"/>
  </wsdl:message>
  <wsdl:message name="setAlarmReportingResponse">
    <wsdl:documentation>
      <p>The setAlarmReporting response message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtopHeader" element="hdr:header"/>
    <wsdl:part name="mtopBody" element="ac:setAlarmReportingResponse"/>
  </wsdl:message>
  <wsdl:message name="setAlarmReportingException">
    <wsdl:documentation>
      <p>The setAlarmReporting exception message.</p>
    </wsdl:documentation>
    <wsdl:part name="mtopBody" element="ac:setAlarmReportingException"/>
  </wsdl:message>
</wsdl:definitions>
