<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourcePerformanceManagement - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-PerformanceManagementControlV1-0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rpm/wsdl/pmc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rpm/wsdl/pmc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourcePerformanceManagement</p>
    <p>Module: PerformanceManagementControl Service Interface WSDL PortType Module</p>
    <p>Description: This module contains all the mTOP PerformanceManagementControl Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rpm/wsdl/pmc/v1-0" location="PerformanceManagementControlMessages.wsdl"/>
  <wsdl:portType name="PerformanceManagementControl">
    <wsdl:documentation>
      <p>The PerformanceManagementControl porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="clearPmData">
      <wsdl:input message="tns:clearPmDataRequest"/>
      <wsdl:output message="tns:clearPmDataResponse"/>
      <wsdl:fault name="clearPmDataException" message="tns:clearPmDataException"/>
    </wsdl:operation>
    <wsdl:operation name="disablePmData">
      <wsdl:input message="tns:disablePmDataRequest"/>
      <wsdl:output message="tns:disablePmDataResponse"/>
      <wsdl:fault name="disablePmDataException" message="tns:disablePmDataException"/>
    </wsdl:operation>
    <wsdl:operation name="enablePmData">
      <wsdl:input message="tns:enablePmDataRequest"/>
      <wsdl:output message="tns:enablePmDataResponse"/>
      <wsdl:fault name="enablePmDataException" message="tns:enablePmDataException"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
