<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceProvisioning - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-GuiCutThroughControlV1-0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rp/wsdl/gctc/v1-0" targetNamespace="http://www.tmforum.org/mtop/rp/wsdl/gctc/v1-0">
  <wsdl:documentation>
    <p>DDP: ResourceProvisioning</p>
    <p>Module: GuiCutThroughControl Service Interface WSDL PortType Module</p>
    <p>Description: This module contains all the mTOP GuiCutThroughControl Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/rp/wsdl/gctc/v1-0" location="GuiCutThroughControlMessages.wsdl"/>
  <wsdl:portType name="GuiCutThroughControl">
    <wsdl:documentation>
      <p>The GuiCutThroughControl porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
    </wsdl:documentation>
    <wsdl:operation name="destroyGct">
      <wsdl:input message="tns:destroyGctRequest"/>
      <wsdl:output message="tns:destroyGctResponse"/>
      <wsdl:fault name="destroyGctException" message="tns:destroyGctException"/>
    </wsdl:operation>
    <wsdl:operation name="getGctProfileInfo">
      <wsdl:input message="tns:getGctProfileInfoRequest"/>
      <wsdl:output message="tns:getGctProfileInfoResponse"/>
      <wsdl:fault name="getGctProfileInfoException" message="tns:getGctProfileInfoException"/>
    </wsdl:operation>
    <wsdl:operation name="launchGct">
      <wsdl:input message="tns:launchGctRequest"/>
      <wsdl:output message="tns:launchGctResponse"/>
      <wsdl:fault name="launchGctException" message="tns:launchGctException"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
