<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTestManagement - Copyright TeleManagement Forum 2014 -->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rt/wsdl/rtsc/v1-0" name="mTOP-ResourceTestSpecControl-V1-0" targetNamespace="http://www.tmforum.org/mtop/rt/wsdl/rtsc/v1-0">
	<wsdl:import namespace="http://www.tmforum.org/mtop/rt/wsdl/rtsc/v1-0" location="ResourceTestSpecControlMessages.wsdl"/>
	<wsdl:documentation>
		<p>DDP: ResourceTest Management</p>
		<p>Module: Resource Test Spec Control Service Interface WSDL PortType Module</p>
		<p>Description: This module contains all the mTOP Resource Test Spec Control Service Interface PortType WSDL definitions common to both Web Service deployment profiles; SOAP/HTTP and SOAP/JMS.</p>
		<p>Version: 1.0</p>
	</wsdl:documentation>
	<wsdl:portType name="ResourceTestSpecControl">
		<wsdl:documentation>
			<p>The ResourceTestSpecControl porttype (interface) common to both RPC (synchronous) and MSG (asynchronous) based client/server communication patterns.</p>
		</wsdl:documentation>
		<!-- createResourceTestSpec operation-->
		<wsdl:operation name="createResourceTestSpec">
			<wsdl:input message="tns:createResourceTestSpecRequest"/>
			<wsdl:output message="tns:createResourceTestSpecResponse"/>
			<wsdl:fault name="createResourceTestSpecException" message="tns:createResourceTestSpecException"/>
		</wsdl:operation>
		<!-- modifyResourceTestSpec operation-->
		<wsdl:operation name="modifyResourceTestSpec">
			<wsdl:input message="tns:modifyResourceTestSpecRequest"/>
			<wsdl:output message="tns:modifyResourceTestSpecResponse"/>
			<wsdl:fault name="modifyResourceTestSpecException" message="tns:modifyResourceTestSpecException"/>
		</wsdl:operation>
		<!-- getResourceTestSpec operation-->
		<wsdl:operation name="getResourceTestSpec">
			<wsdl:input message="tns:getResourceTestSpecRequest"/>
			<wsdl:output message="tns:getResourceTestSpecResponse"/>
			<wsdl:fault name="getResourceTestSpecException" message="tns:getResourceTestSpecException"/>
		</wsdl:operation>
		<!-- deleteResourceTestSpec operation-->
		<wsdl:operation name="deleteResourceTestSpec">
			<wsdl:input message="tns:deleteResourceTestSpecRequest"/>
			<wsdl:output message="tns:deleteResourceTestSpecResponse"/>
			<wsdl:fault name="deleteResourceTestSpecException" message="tns:deleteResourceTestSpecException"/>
		</wsdl:operation>
	</wsdl:portType>
</wsdl:definitions>
