<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ResourceTestManagement - Copyright TeleManagement Forum 2014 -->
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/rt/wsdl/rtsc/v1-0" name="mTOP-ResourceTestSpecControl-V1-0" targetNamespace="http://www.tmforum.org/mtop/rt/wsdl/rtsc/v1-0">
	<wsdl:import namespace="http://www.tmforum.org/mtop/rt/wsdl/rtsc/v1-0" location="ResourceTestSpecControlPortType.wsdl"/>
	<wsdl:documentation>
		<p>DDP: ResourceTestManagement</p>
		<p>Module: Resource Test Spec Control Service Interface WSDL JMS Module</p>
		<p>Description: This module contains all the mTOP ResourceTestSpecControl Service Interface WSDL definitions for the Web Service deployment profile with SOAP/JMS binding.</p>
		<p>Version: 1.0</p>
	</wsdl:documentation>
	<wsdl:binding name="ResourceTestSpecControlSoapJmsBinding" type="tns:ResourceTestSpecControl">
		<wsdl:documentation>
			<p>SOAP JMS binding definitions of the operations of the ResourceTestSpecControl portType (interface)</p>
		</wsdl:documentation>
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
		<!-- startTest operation -->
		<wsdl:operation name="createResourceTestSpec">
			<soap:operation style="document"/>
			<wsdl:input>
				<soap:header message="tns:createResourceTestSpecRequest" part="mtopHeader" use="literal"/>
				<soap:body parts="mtopBody" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="tns:createResourceTestSpecResponse" part="mtopHeader" use="literal"/>
				<soap:body parts="mtopBody" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="createResourceTestSpecException">
				<soap:fault name="createResourceTestSpecException" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<!-- modifyResourceTestSpec operation -->
		<wsdl:operation name="modifyResourceTestSpec">
			<soap:operation style="document"/>
			<wsdl:input>
				<soap:header message="tns:modifyResourceTestSpecRequest" part="mtopHeader" use="literal"/>
				<soap:body parts="mtopBody" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="tns:modifyResourceTestSpecResponse" part="mtopHeader" use="literal"/>
				<soap:body parts="mtopBody" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="modifyResourceTestSpecException">
				<soap:fault name="modifyResourceTestSpecException" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<!-- getResourceTestSpec operation -->
		<wsdl:operation name="getResourceTestSpec">
			<soap:operation style="document"/>
			<wsdl:input>
				<soap:header message="tns:getResourceTestSpecRequest" part="mtopHeader" use="literal"/>
				<soap:body parts="mtopBody" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="tns:getResourceTestSpecResponse" part="mtopHeader" use="literal"/>
				<soap:body parts="mtopBody" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="getResourceTestSpecException">
				<soap:fault name="getResourceTestSpecException" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
		<!-- deleteResourceTestSpec operation -->
		<wsdl:operation name="deleteResourceTestSpec">
			<soap:operation style="document"/>
			<wsdl:input>
				<soap:header message="tns:deleteResourceTestSpecRequest" part="mtopHeader" use="literal"/>
				<soap:body parts="mtopBody" use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:header message="tns:deleteResourceTestSpecResponse" part="mtopHeader" use="literal"/>
				<soap:body parts="mtopBody" use="literal"/>
			</wsdl:output>
			<wsdl:fault name="deleteResourceTestSpecException">
				<soap:fault name="deleteResourceTestSpecException" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ResourceTestSpecControlJms">
		<wsdl:documentation>
			<p>Example of the ResourceTestSpecControl WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
		</wsdl:documentation>
		<wsdl:port name="ResourceTestSpecControlSoapJms" binding="tns:ResourceTestSpecControlSoapJmsBinding">
			<soap:address location="jms://aserver/mtosi/ResourceTestSpecControl"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
