<?xml version="1.0" encoding="UTF-8"?>
<!-- TMF854 Version 1.1 - Copyright TeleManagement Forum 2005, 2006 -->
<wsdl:definitions xmlns:tmf854WS="tmf854.v1.ws" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="tmf854.v1.ws" name="TMF854-ConfigurationService">
  <!-- ================ -->
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_http/EquipmentInventoryMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_http/InventoryRetrievalSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_http/ManagedElementMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_http/MultiLayerSubnetworkMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_http/OperationsSystemMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_http/ProtectionMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_http/TransmissionDescriptorMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_jms/EquipmentInventoryMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_jms/InventoryRetrievalSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_jms/ManagedElementMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_jms/MultiLayerSubnetworkMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_jms/OperationsSystemMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_jms/ProtectionMgrSOAP.wsdl"/>
  <wsdl:import namespace="tmf854.v1.ws" location="../binding/soap_jms/TransmissionDescriptorMgrSOAP.wsdl"/>
  <!-- ================ -->
  <wsdl:service name="ConfigurationService">
    <!-- ================ -->
    <wsdl:port name="EquipmentInventoryMgrHttp" binding="tmf854WS:EquipmentInventoryMgrSoapHTTPBinding">
      <soap:address location="http://aserver/mtosi/v1/EquipmentInventoryMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="InventoryRetrievalHttp" binding="tmf854WS:InventoryRetrievalSoapHTTPBinding">
      <soap:address location="http://aserver/mtosi/v1/InventoryRetrieval"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="ManagedElementMgrHttp" binding="tmf854WS:ManagedElementMgrSoapHTTPBinding">
      <soap:address location="http://aserver/mtosi/v1/ManagedElementMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="MultiLayerSubnetworkMgrHttp" binding="tmf854WS:MultiLayerSubnetworkMgrSoapHTTPBinding">
      <soap:address location="http://aserver/mtosi/v1/MultiLayerSubnetworkMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="OperationsSystemMgrHttp" binding="tmf854WS:OperationsSystemMgrSoapHTTPBinding">
      <soap:address location="http://aserver/mtosi/v1/OperationsSystemMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="ProtectionMgrHttp" binding="tmf854WS:ProtectionMgrSoapHTTPBinding">
      <soap:address location="http://aserver/mtosi/v1/ProtectionMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="TransmissionDescriptorMgrHttp" binding="tmf854WS:TransmissionDescriptorMgrSoapHTTPBinding">
      <soap:address location="http://aserver/mtosi/v1/TransmissionDescriptorMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="EquipmentInventoryMgrJms" binding="tmf854WS:EquipmentInventoryMgrSoapJMSBinding">
      <soap:address location="http://aserver/mtosi/v1/EquipmentInventoryMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="InventoryRetrievalJms" binding="tmf854WS:InventoryRetrievalSoapJMSBinding">
      <soap:address location="http://aserver/mtosi/v1/InventoryRetrieval"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="ManagedElementMgrJms" binding="tmf854WS:ManagedElementMgrSoapJMSBinding">
      <soap:address location="http://aserver/mtosi/v1/ManagedElementMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="MultiLayerSubnetworkMgrJms" binding="tmf854WS:MultiLayerSubnetworkMgrSoapJMSBinding">
      <soap:address location="http://aserver/mtosi/v1/MultiLayerSubnetworkMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="OperationsSystemMgrJms" binding="tmf854WS:OperationsSystemMgrSoapJMSBinding">
      <soap:address location="http://aserver/mtosi/v1/OperationsSystemMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="ProtectionMgrJms" binding="tmf854WS:ProtectionMgrSoapJMSBinding">
      <soap:address location="http://aserver/mtosi/v1/ProtectionMgr"/>
    </wsdl:port>
    <!-- ================ -->
    <wsdl:port name="TransmissionDescriptorMgrJms" binding="tmf854WS:TransmissionDescriptorMgrSoapJMSBinding">
      <soap:address location="http://aserver/mtosi/v1/TransmissionDescriptorMgr"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
