<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="TIP-TPControl_OrderV1-0" 
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
xmlns:tns="http://www.tmforum.org/tip/TPC_ord/wsdl/v1-0" 
targetNamespace="http://www.tmforum.org/tip/TPC_ord/wsdl/v1-0">

  <wsdl:import namespace="http://www.tmforum.org/tip/TPC_ord/wsdl/v1-0" 
  location="TPCOrderMessages.wsdl"/>
  <wsdl:portType name="TPControl">
  
    <wsdl:operation name="execute_FTP_Create_Order">
      <wsdl:input message="tns:execute_FTP_Create_Order_Request"/>
      <wsdl:output message="tns:execute_FTP_Create_Order_Response"/>
      <wsdl:fault name="execute_FTP_Create_Order_Exception" 
					  message="tns:execute_FTP_Create_Order_Exception"/>
    </wsdl:operation>    
    
    <wsdl:operation name="execute_GTP_Create_Order">
      <wsdl:input message="tns:execute_GTP_Create_Order_Request"/>
      <wsdl:output message="tns:execute_GTP_Create_Order_Response"/>
      <wsdl:fault name="execute_GTP_Create_Order_Exception" 
					  message="tns:execute_GTP_Create_Order_Exception"/>
    </wsdl:operation>
    
    <wsdl:operation name="execute_TP_setTerminationPointData_Order">
      <wsdl:input message="tns:execute_TP_setTerminationPointData_Order_Request"/>
      <wsdl:output message="tns:execute_TP_setTerminationPointData_Order_Response"/>
      <wsdl:fault name="execute_TP_setTerminationPointData_Order_Exception" 
					  message="tns:execute_TP_setTerminationPointData_Order_Exception"/>
    </wsdl:operation>         
  <!--
	...
	-->            
  </wsdl:portType>

</wsdl:definitions>
