<?xml version="1.0" encoding="UTF-8"?>
<!-- mTOP DDP - OM ManageResourceInventory - Copyright TeleManagement Forum 2007 -->
<wsdl:definitions name="mTOP-MdRetrievalHttpV1-0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.tmforum.org/mtop/mri/wsdl/mdr/v1-0" targetNamespace="http://www.tmforum.org/mtop/mri/wsdl/mdr/v1-0">
  <wsdl:documentation>
    <p>DDP: Manage Resource Inventory</p>
    <p>Module: MD Retrieval Service Interface WSDL HTTP Module</p>
    <p>Description: This module contains the mTOP MD Retrieval Service Interface WSDL definitions for the Web Service deployment profile with SOAP/HTTP binding.</p>
    <p>Version: 1.0</p>
  </wsdl:documentation>
  <wsdl:import namespace="http://www.tmforum.org/mtop/mri/ws/mdr/v1-0" location="MdRetrievalMessages.wsdl"/>
  <wsdl:portType name="MdRetrieval_RPC">
    <wsdl:documentation>
      <p>The MdRetrieval porttype (interface) for RPC (synchronous) based client/server communication patterns. All SIT operations use the specific get"ObjectType"Iterator operation to handle multiple responses.</p>
    </wsdl:documentation>
    <wsdl:operation name="getAllManagementDomainNames">
      <wsdl:documentation>
        <p>This SRR operation returns the name of each Management Domain (MD) associated with a top-level OS.</p>
      </wsdl:documentation>
      <wsdl:input message="tns:getAllManagementDomainNamesRequest"/>
      <wsdl:output message="tns:getAllManagementDomainNamesResponse"/>
      <wsdl:fault name="getAllManagementDomainNamesException" message="tns:getAllManagementDomainNamesException"/>
    </wsdl:operation>
    <wsdl:operation name="getAllManagementDomains">
      <wsdl:documentation>
        <p>This SRR operation returns the data structure for each Management Domain (MD) associated with a top-level OS.</p>
      </wsdl:documentation>
      <wsdl:input message="tns:getAllManagementDomainsRequest"/>
      <wsdl:output message="tns:getAllManagementDomainsResponse"/>
      <wsdl:fault name="getAllManagementDomainsException" message="tns:getAllManagementDomainsException"/>
    </wsdl:operation>
    <wsdl:operation name="getManagementDomain">
      <wsdl:documentation>
        <p>This SRR operation returns the data structure associated with a given Management Domain (MD) identified by the provided mdName.</p>
      </wsdl:documentation>
      <wsdl:input message="tns:getManagementDomainRequest"/>
      <wsdl:output message="tns:getManagementDomainResponse"/>
      <wsdl:fault name="getManagementDomainException" message="tns:getManagementDomainException"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="MdRetrievalSoapHttpBinding" type="tns:MdRetrieval_RPC">
    <wsdl:documentation>
      <p>SOAP HTTP binding definitions of the operations of the MdRetrieval RPC portType (interface)</p>
    </wsdl:documentation>
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getAllManagementDomainNames">
      <soap:operation soapAction="getAllManagementDomainNames" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getAllManagementDomainNamesRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllManagementDomainNamesResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllManagementDomainNamesException">
        <soap:fault name="getAllManagementDomainNamesException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getAllManagementDomains">
      <soap:operation soapAction="getAllManagementDomains" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getAllManagementDomainsRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getAllManagementDomainsResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getAllManagementDomainsException">
        <soap:fault name="getAllManagementDomainsException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
    <wsdl:operation name="getManagementDomain">
      <soap:operation soapAction="getManagementDomain" style="document"/>
      <wsdl:input>
        <soap:header message="tns:getManagementDomainRequest" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:getManagementDomainResponse" part="mtopHeader" use="literal"/>
        <soap:body parts="mtopBody" use="literal"/>
      </wsdl:output>
      <wsdl:fault name="getManagementDomainException">
        <soap:fault name="getManagementDomainException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="MdRetrievalHttp">
    <wsdl:documentation>
      <p>Example of the MdRetrieval WSDL Service definition as a deployment example of this mTOP Service Interface. It is expected to be modified to match the specific deployment configuration in a service provider's CCV.</p>
    </wsdl:documentation>
    <wsdl:port name="MdRetrievalSoapHttp" binding="tns:MdRetrievalSoapHttpBinding">
      <soap:address location="http://aserver/mtosi/MdRetrieval"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
